version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: delei-portainer
    working_dir: /
    restart: always
    privileged: true
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "bridge"
    ports:
      - "9000:9000"
      - "9443:9443"