# [Server]
server:
  address: 127.0.0.1
  port: 9999
  servlet:
    context-path: /interview
    session:
      timeout: -1
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8
# [Spring]
spring:
  application:
    name: interview