# [Server]
server:
  address: 0.0.0.0
  port: 8101
# [Spring]
spring:
  application:
    name: interview-service02
  main:
    banner-mode: console
  cloud:
    nacos:
      discovery:
        server-addr: server.deleiguo.com:8848
        namespace: 1bf7f264-35d4-49e9-acbc-29a98ff840a4
        group: DELEIGUO_GROUP

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always