version: '3'

services:
  master:
    image: redis:6.2.11-alpine
    container_name: dg-redis-master
    restart: always
    privileged: true
    command: redis-server --requirepass deleiguo --appendonly yes
    volumes:
      - ./data/master:/data
    ports:
      - 6379:6379
    networks:
      redis_net:
        ipv4_address: 172.16.0.10 
  slave1:
    image: redis:6.2.11-alpine
    container_name: dg-redis-slave1
    restart: always
    privileged: true
    command: redis-server --slaveof dg-redis-master 6379  --requirepass deleiguo --masterauth deleiguo  --appendonly yes
    volumes:
      - ./data/slave1:/data
    ports:
      - 6380:6379
    depends_on:
      - master
    networks:
      redis_net:
        ipv4_address: 172.16.0.11
  slave2:
    image: redis:6.2.11-alpine
    container_name: dg-redis-slave2
    restart: always
    privileged: true
    command: redis-server --slaveof dg-redis-master 6379  --requirepass deleiguo --masterauth deleiguo  --appendonly yes
    volumes:
      - ./data/slave2:/data
    ports:
      - 6381:6379
    depends_on:
      - master
    networks:
      redis_net:
        ipv4_address: 172.16.0.12

networks:
  redis_net:
    ipam:
      config:
      - subnet: 172.16.0.0/24