# [Server]
server:
  address: 127.0.0.1
  port: 6100
  servlet:
    context-path: /interview
    session:
      timeout: -1
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8
# [Spring]
spring:
  application:
    name: interview
  profiles:
    include: dg
  main:
    banner-mode: console
  datasource:
    url: jdbc:mysql://server.deleiguo.com:3306/deleiguo_interview?useUnicode=true&characterEncoding=utf8
    username: root
    password: deleiguo
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1